apiVersion: v1
kind: Secret
metadata:
  name: shopping-cart-secret
  namespace: shopping-cart
type: Opaque
StringData:
  DB_PASSWORD: "shoppassword"
  MYSQL_ROOT_PASSWORD: "root@123"
  MYSQL_PASSWORD: "shoppassword"