# Database Credentials
db.driverName = ${DB_DRIVER_NAME}
db.connectionString = ${DB_CONNECTION_STRING}
db.username = ${DB_USERNAME}
db.password = ${DB_PASSWORD}

#Mailer Credentials
mailer.email=${MAILER_EMAIL}
mailer.password=${MAILER_PASSWORD}
