# Database Credentials
db.driverName = com.mysql.cj.jdbc.Driver
db.connectionString = jdbc:mysql://localhost:3306/shopping-cart
db.username = root
db.password = root@123

#Mailer Credentials
mailer.email=rk31saxena@gmail.com
mailer.password=rzgl kxjv zqny yelx